# Generated by Django 4.0.2 on 2022-02-14 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_post_likes_postlike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postlike',
            options={'ordering': ['created']},
        ),
    ]
