# Generated by Django 4.0.2 on 2022-02-15 13:23

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_userdetails_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='last_request',
            field=models.DateTimeField(default=django.utils.datetime_safe.datetime.now),
        ),
    ]
